gurdy:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  # Position Controllers
  head_upper_leg_M1_controller:
    type: effort_controllers/JointPositionController
    joint: head_upper_leg_M1
    pid: {p: 1.0, i: 1.0, d: 0.0}
  upper_leg_M1_lower_leg_M1_controller:
    type: effort_controllers/JointPositionController
    joint: upper_leg_M1_lower_leg_M1
    pid: {p: 1.0, i: 1.0, d: 0.0}
  head_upper_leg_M2_controller:
    type: effort_controllers/JointPositionController
    joint: head_upper_leg_M2
    pid: {p: 1.0, i: 1.0, d: 0.0}
  upper_leg_M2_lower_leg_M2_controller:
    type: effort_controllers/JointPositionController
    joint: upper_leg_M2_lower_leg_M2
    pid: {p: 1.0, i: 1.0, d: 0.0}
  head_upper_leg_M3_controller:
    type: effort_controllers/JointPositionController
    joint: head_upper_leg_M3
    pid: {p: 1.0, i: 1.0, d: 0.0}
  upper_leg_M3_lower_leg_M3_controller:
    type: effort_controllers/JointPositionController
    joint: upper_leg_M3_lower_leg_M3
    pid: {p: 1.0, i: 1.0, d: 0.0}